var config = {
		ui_config : {
			menu_hover_font_color:"#EEE",
			title : "Support Central",
			head_image : "images/head_image.png",
			head_text_system : "Data Protection & Availability",
			loading_image:"images/loadingPage.gif",
			head_text_application : "Support Central",
			foot_info : "This website is best viewed using Chrome, Firefox and IE 9+ web browsers.<br/>",
			rights_info : "Copyright 2014 EMC.<br/>"
		},
		page_config:{
			role1_id:2,
			role2_id:3,
			search_emp_default_text:"Enter badge number or NT account or lastname, firstname",
			delete_photo_tooltip:"Remove role from this user.",
			search_emp_tooltip:"Invalid input!",
			search_emp_null:"There is no employee found!",
			save_emp_null:"Please search employee first.",
			photo_hint:"Click to view his or her information. ",
			confirm_delete_photo:"Are you sure to remove role from this user ? ",
			input_natural_num:"Please enter a natural number.",
			input_num_or_empty:"Please enter a natural number or leave blank to ignore.",
			add_symptom_def:"Add Symptom Definition",
			remove_symptom_def:"Remove Symptom Definition",
			add_symptom_name:"Add Symptom Name",
			remove_symptom_name:"Remove Symptom Name",
			delete_symptom_name_success:"Symptom Name removed successfully!",
			delete_symptom_name_error:"Can't delete this symptom name. Some bug symptoms are using this symptom name.",
			delete_symptom_success:"Symptom removed successfully!",
			save_symptom_success:"Symptom saved successfully!",
			save_symptom_error:"Symptom saved in error!",
			save_symptom_name_success:"Symptom Name saved successfully!",
			save_symptom_name_error:"Symptom Name saved in error!",
			save_symptom_data_success:"Symptom Data saved successfully!",
			delete_symptom_data_success:"Symptom Data deleted successfully!",
			fill_fields_error:"Please enter valid values in the highlighted fields.",
			software_input_default_text:"Click to select DDOS levels.",
			hardware_input_default_text:"Click to select model numbers.",
			add_bug_def:"Add Bug Definition",
			remove_bug_def:"Remove Bug Definition",
			edit_bug_def:"Edit Bug Definition",
			export_bug_def:"Export this bug",
			show_bug_def:"Link to Knowledge Base Article",
			category_hint_text:"Select an existing category or enter a new one.",
			sortable_column_hint:"Click to sort by this field.",
			sortable_operations_column_hint:"Click to sort by number of bug referenced.",
			delete_bug_success:"Bug definition is deleted successfully!",
			delete_bug_error:"Error occured in deleting Bug definition!",
			save_bug_success:"Bug definition is saved successfully!",
			save_bug_error:"Error occured in saving Bug definition!",
			bugzilla_url_prefix:"https://bugzilla.datadomain.com/bugzilla/show_bug.cgi?id=",
			confirm_leave_page:"Some fields have been changed which are not saved.",
			symptom_expression_error:"The expression of symptoms is not in the right format!",
			scan_bugs_success:"Bug Scan completed! {num} bug(s) matched.",
			scan_bugs_failed:"Some error(s) occurred when scanning bugs! ",
			no_bug_selected:"No bug(s) selected to scan!",
			test_bug_error:"There is 0 bug matches.",
			test_bug_sn_prompt:"Please input serial number of the machine to be tested.<br/>(Hint: You can ignore this field to test upon all machines. But it will take longer time.)",
			ajax_timeout_threshold:60000,
			test_bug_timeout_confirm:"This test task has executed more than {time} seconds. Do you want to stop it?",
			items_per_page:8,
			num_display_entries:5,
			prescan_schedule_tip:"New symptom name. 'Pre-scan' will be scheduled in {time}",
			bug_page_tooltip:"Press the \"Manage Bug Definitions\" button after selecting which bug definitions you'd like to manage.",
			edit_symptom_name:"Click to edit this pattern.",
			symptom_pattern_plus:"Add a pattern.",
			symptom_pattern_minus:"Delete this pattern.",
			symptom_pattern_value:"Please input a value",
			slideup_tooltip:"Click to collapse.",
			slidedown_tooltip:"Click to expand.",
			search_symptom_tooltip:"Search symptoms(click to expand).",
			select_symptom_data:"Select symptom data.",
			select_table:"Select section.",
			select_section:"Select section or variable.",
			select_variable:"Select variable.",
			select_mapping:"Select mapping.",
			select_table_set:"Select table.",
			select_table_subset:"Select \"key\" column.",
			select_domain:"Select \"from\" column.",
			select_codomian:"Select \"to\" column.",
			substitute_tooltip:"Click to substitute the pattern expression.",
			add_substitute:"Add a substitute.",
			delete_substitute:"Delete a substitute.",
			back_level_item:"...",
			id_splitter:"#",
			path_splitter:",",
			tip_splitter:".",
			delete_substitution_confirm:"Are you sure to delete this substitution?",
			delete_symptom_confirm:"Are you sure to delete this symptom?",
			delete_referenced_symptom:"This symptom can not be deleted, because it is referenced by another symptom.",
			save_before_test_symptom:"Please save this symptom before testing it.",
			symptom_zero_referenced:"This symptom has not been referenced by any bug.",
			symptom_referenced : "This symptom is referenced by {bugNum} bugs. ID of these bugs are: {bugs}. Click for details. ",
			//bug column option
			save_option_info: "Save it as your customized layout. It will display directly next time",
			select_option_error: "You can only select 8 columns at most(including the mandatory ones).",
			save_option_success: "Your layout has been saved successfully!",
			save_option_error: "Your layout saved in error!"
		},
		test_config:{
			isHijack:false
		}
	};